Fixed major memory usage issues
FunkinCrew/Funkin pull request #1083
Opened 2021-05-13 00:15 UTC by Naishaline

When assets are loaded into the game, they are never unloaded. This can cause many issues related to significant RAM usage. Most issues that complain about characters loading as black boxes are from running out of memory. This also causes slowdowns as the system runs out of RAM. I found these issues myself playing the game normally for the first time, and it seems like a very critical issue. 
I'll note that in the cases where assets are loading as black boxes, that's more from devices with 4 gigs of RAM or so, so it may not be able to load the assets initially at all when loading the game. Because of that, this request may not fix all instances of black boxes from happening, but I think it'll help/prevent it in a lot of cases because it'll keep memory as low as it can.

Anyways, my solution overwrites the Haxe `add` command, and adds the object you're adding to an array of of tracked assets, then it loads the asset in as it would normally. Then in key areas (like when a song gets finished, or when going from a menu to a song), it'll unload the assets using the Haxe `remove` command. There are a few areas I manually unloaded some assets, like the GameOverSubstate, just because there's only one or two assets ever loaded.

TL;DR: This cleanly and dynamically keeps track of and removes unneeded assets to stop clogging up memory. This fixes some pretty significant issues.

(Memory usage outright)
#856 #280 #58 

(Black boxes/Characters just not loading)
#1021 #992 (There are more I just don't want to search through it all lol)

Let me know if you have any questions or comments! Pretty happy with how clean the implementation is.

2021-05-13 06:51 UTC, PurpleButNotALight approved these changes
we must support the low end gamers, ninjamuffin pls merge.

2021-05-13 12:00 UTC, nickpythonluajava commented
raspi 4: **My time has come**

2021-05-13 12:00 UTC, nickpythonluajava approved these changes

2021-05-13 14:46 UTC, hdboye approved these changes
ninja, if u see this, merge or ur a poopy fart

2021-05-13 14:48 UTC, nickpythonluajava commented
> ninja, if u see this, merge or ur a poopy fart

insult of the year

2021-05-13 14:48 UTC, hdboye commented
i know im a baddie

2021-05-13 16:43 UTC, VMGuy23 commented
> raspi 4: **My time has come**

I have a Raspberry Pi 4 (4GB RAM) and it would be cool to see the FPS on that thing, and play the game without squares

2021-05-15 16:11 UTC, trayfellow commented
> ninja, if u see this, merge or ur a poopy fart

hdboye when ninjamuffin doesn't merge this : https://youtu.be/EEuFbmmuqK4

2021-05-15 16:27 UTC, VMGuy23 approved these changes
Nice

I need this

2021-05-16 21:25 UTC, trayfellow approved these changes

2021-05-16 21:47 UTC, NotHyper-474 approved these changes

2021-05-17 12:08 UTC, Rs232k commented
Sad, maybe it's works in desktop, but in mobile created crash.

2021-05-17 14:23 UTC, Naishaline commented
> Sad, maybe it's works in desktop, but in mobile created crash.

How did you go about compiling for mobile?

2021-05-17 14:55 UTC, Hendicted commented
what about the songs that get loaded in? from what i'm seeing they dont seem to be unloading

2021-05-18 15:31 UTC, Steviegt6 requested changes
There appears to be quite a lot of boiler-plate code used here. Would a single class that serves as an asset manager not work better? I see no reason for using what appear to be the same methods over and over in a few different classes.

Edit: Nevermind, missed the fact that you're overriding methods. My bad.

2021-05-18 22:25 UTC, Hendicted commented
actually since the game uses openfl libraries you could try to use [https://api.openfl.org/openfl/utils/Assets.html](the unloadLibrary() function) of openfl.utils.Assets. i could make a proof of concept out of it

2021-05-20 17:34 UTC, Steviegt6 commented
Frankly, if you were to make a PoC then you may as well make an alternative PR with similar goals.

2021-05-23 11:41 UTC, notdonxd requested changes
You should add this function in other states, like the Pause menu.

2021-05-23 16:32 UTC, Hendicted commented
> Frankly, if you were to make a PoC then you may as well make an alternative PR with similar goals.

i tried it! but unfourtanetly the results were dissapointing

basically what the function actually does is unload the library and it's paths, not unload the library from memory, which i find dissapointing

2021-06-03 23:34 UTC, Michael82548 commented
#1222

2022-09-25 23:46 UTC, MemeHoovy approved these changes

2022-10-15 22:45 UTC, TheGaloXx approved these changes
THIS IS SO GOOD, IM TRYING THIS OUT

2022-12-02 12:28 UTC, APRO716 approved these changes

2024-05-08 00:25 UTC, closed without merging