Easter Eggo + AnimationDebug Tweaks.
FunkinCrew/Funkin pull request #1760
Opened 2021-09-17 19:11 UTC by KitOdin

Added a little easter egg in the menu ;)
also tweaked the hidden ass animation debug menu only exclusive to debug build targets lmao.

2021-09-20 16:19 UTC, Infinity48Games commented
Does not work. It gives these errors on compile:
```
source/LatencyState.hx:19: characters 26-40 : Type not found : FlxGridOverlay
source/LatencyState.hx:66: characters 7-20 : Type not found : controls.BACK
source/AnimationDebug.hx:164: characters 7-22 : Type not found : controls.ACCEPT
```
To fix this just add:
```
private var controls(get, never):Controls;

	inline function get_controls():Controls
		return PlayerSettings.player1.controls;
```
To the beginning of both classes and add `import flixel.addons.display.FlxGridOverlay;` to the beginning of LatencyState.hx.

2021-09-20 17:16 UTC, KitOdin commented
fixed :)

2021-09-21 09:15 UTC, somefnfplayerlol requested changes

2021-09-21 09:15 UTC, somefnfplayerlol commented on source/AnimationDebug.hx
> +
tf is this?

2021-09-21 15:34 UTC, KitOdin commented on source/AnimationDebug.hx
> +
dunno.

2021-10-01 17:18 UTC, prokube commented on source/AnimationDebug.hx
> +
me when
``` diff
-
+                 
```

2024-05-08 00:25 UTC, closed without merging