update templates (WIP)
FunkinCrew/Funkin pull request #1772
Opened 2021-09-21 22:20 UTC by AbnormalPoof

2021-09-22 01:57 UTC, prokube commented
> Bug and compiling issue templates: Added disclaimer saying to type in the body and not the title
> PR enhancement template: added disclaimer saying not to add thousands of commits from other engines

you can't win an argument against an idiot

2021-09-22 16:25 UTC, Cheemsandfriends approved these changes

2021-09-22 16:25 UTC, Cheemsandfriends commented on .github/PULL_REQUEST_TEMPLATE/enhancement.md
> +#### Do NOT make PRs with thousands of commits from other engines, as they will likely never be official.
This is really needed

2021-09-22 19:26 UTC, AbnormalPoof commented on .github/PULL_REQUEST_TEMPLATE/enhancement.md
> +#### Do NOT make PRs with thousands of commits from other engines, as they will likely never be official.
about time someone addressed the issue

2021-09-30 15:59 UTC, Steviegt6 requested changes

2021-09-30 15:59 UTC, Steviegt6 commented on .github/PULL_REQUEST_TEMPLATE/enhancement.md
> +#### Do NOT make PRs with thousands of commits from other engines, as they will likely never be official.
> `as they will likely never be official`
Unnecessary bloat.

2021-10-01 03:53 UTC, AbnormalPoof commented
@Steviegt6 better?

2021-10-01 15:52 UTC, Steviegt6 commented
> @Steviegt6 better?

Yeah. Doubt anyone making those kinds of PRs would understand how cherry-picking works but it's a definite improvement. Thanks!

2021-10-01 15:52 UTC, Steviegt6 approved these changes

2021-10-01 16:22 UTC, AbnormalPoof commented
No problem lol

2024-05-08 00:25 UTC, closed without merging