HashLink compatibility
FunkinCrew/Funkin pull request #1831
Opened 2021-10-09 18:46 UTC by libauror-a

fuck neko, embrasse hashlink, just some problems, NGio dosen't work because you'll get this error `FATAL ERROR : Failed to load library ssl.hdll` so i had to jankly fix the error, (probally modders shoudn't use the NG shit in their mods/engines and shoud be coded out) probally gimme suggestions because this is kida bad, but it still works!

2021-10-09 19:04 UTC, ACrazyTown requested changes

2021-10-09 19:04 UTC, ACrazyTown commented on source/Discord.hx
> +		trace("Discord Client isn't going to start because this is a cpp client, go home.");
looks good, but shouldn't it be "because this is *not* a cpp client"?

2021-10-09 22:17 UTC, DotWith commented
Also do the same with newgrounds

2021-10-10 06:33 UTC, ThePlank commented
> OpenGLRenderer crash

i think lime and openfl are outdated

2021-10-10 17:23 UTC, DotWith commented
> > OpenGLRenderer crash
> 
> i think lime and openfl are outdated

Thanks I was installing a dev openfl from git. It now works with non git version.

2021-10-21 21:13 UTC, closed without merging

2021-11-03 18:05 UTC, KitOdin commented
since when was there a secret repo for fnf?

2021-11-03 18:06 UTC, Steviegt6 commented
> since when was there a secret repo for fnf?

For quite some time, how else would they collaboratively develop it?