README.md credits fix
FunkinCrew/Funkin pull request #2977
Opened 2024-07-07 07:00 UTC by JVNpixels

Fixes the README markdown file and gives proper credit to those who contributed to the development of Friday Night Funkin’.

2024-07-07 07:05 UTC, JVNpixels commented
I know there was In-Game credits, but atleast update the GitHub README.

2024-07-07 07:06 UTC, JVNpixels commented
These were to just to start, and maybe you guys could do the rest? I mean you guys know their socials and I dont.

2024-07-07 16:48 UTC, JVNpixels commented
Just to clarify, what needs revision? I was writing this when I was tired and I also just woke up.

2024-07-07 17:06 UTC, JVNpixels commented
Oh I got it now, thanks, I will update this later.

2024-07-07 23:38 UTC, JVNpixels commented
I have added everyone from the development team and contributing help (like sr pelo and tankman), note I only added the developers and helpers, not the Kickstarter or legal stuff, that can be seen with-in the games credits menu.

2024-07-10 22:01 UTC, EliteMasterEric commented
@ninjamuffin99 Does this look good? Any thoughts/additions?

2024-07-10 22:29 UTC, Hundrec requested changes

2024-07-10 22:29 UTC, Hundrec commented on README.md
> +- [MtH](https://twitter.com/emmnyaa) - Featured Guest Musician for "Breakfast (Week 6 Version)
Make sure to add end quotes after Results and Breakfast!

2024-07-10 23:52 UTC, Hundrec commented on README.md
> +- [MtH](https://twitter.com/emmnyaa) - Featured Guest Musician for "Breakfast (Week 6 Version)
Remember to add quotes to Results (Excellent) too :)

2024-07-11 00:20 UTC, Hundrec approved these changes

2024-07-12 01:38 UTC, doggogit requested changes
Some adjustments can be made, as shown here:

2024-07-12 01:38 UTC, doggogit commented on README.md
> +- [SixImpala](https://twitter.com/SixImpala) - Musician
Handle should be changed to:
```suggestion
- [SixImpala](https://twitter.com/siximpalasix) - Musician
```

2024-07-12 01:38 UTC, doggogit commented on README.md
> +- [PennilessRagamuffin](https://twitter.com/PennilessRagamuffin) - Cutscene Animation
Same goes here, accounts are either incorrect or just straight up don't exist.

2024-07-12 01:38 UTC, doggogit commented on README.md
> +- [Will Blanton](https://twitter.com/WillBlanton) - Additional Programming
Abovementioned comment also applies to this user.

2024-07-12 01:38 UTC, doggogit commented on README.md
> +- [Osaka Red LLC: Thomas J Webb](https://twitter.com/ThomasJWebb) - Additional Programming
I believe that the aforementioned people here have been attached to incorrect Twitter accounts or accounts that simply don't exist. 

Maybe someone from the team should chime in and examine and see if they can correct the mistakes and say who does or doesn't have Twitter and/or any other social media platform.

2024-07-12 01:38 UTC, doggogit commented on README.md
> +The full credits can be found in-game, or wherever the credits.json file is.
`The full` can be reverted back to `Full`, and here's the link to `credits.json` as follows:
```suggestion
Full credits can be found in-game, or [in the `credits.json` file](https://github.com/FunkinCrew/funkin.assets/blob/main/exclude/data/credits.json).
```

2024-07-12 01:40 UTC, doggogit commented
> Some adjustments can be made, as shown here:

In addition, maybe move this to its own separate file, like `CREDITS.md`?

2024-07-12 02:30 UTC, JVNpixels commented
> > Some adjustments can be made, as shown here:
> 
> In addition, maybe move this to its own separate file, like `CREDITS.md`?
> 
> Reason being that it might clutter the README.

Alright I will fix this up and make it look nicer, and then make a credits.md file

2024-07-12 02:35 UTC, doggogit commented
> > > Some adjustments can be made, as shown here:
> > 
> > 
> > In addition, maybe move this to its own separate file, like `CREDITS.md`?
> > Reason being that it might clutter the README.
> 
> Alright I will fix this up and make it look nicer, and then make a credits.md file

Sweet! Just make sure to put the CREDITS.md in `docs/` whenever you end up making it.

@EliteMasterEric or @ninjamuffin99, can you guys confirm or provide some of the Twitter links for specific members that were credited/thanked?

2024-07-12 02:37 UTC, JVNpixels commented
Note: I have found links for the following:
Sade
BlairTheUnseriousGuy
Topium
Ragamuffin

2024-07-12 02:39 UTC, doggogit commented
> Note: I have found links for the following: Sade BlairTheUnseriousGuy Topium Ragamuffin

Awesome, I know hazel doesn't use twitter, they use mastodon... but I don't quite the remember the link..

2024-07-12 02:39 UTC, JVNpixels commented
Credits will be up in a sec, I am quite busy rn

2024-07-12 02:41 UTC, doggogit commented
> Credits will be up in a sec, I am quite busy rn

That's fine, take yer time

2024-07-12 02:45 UTC, JVNpixels commented
Should be added now!

2024-07-12 03:24 UTC, doggogit requested changes
Some stuff, idk, didn't like the credits.json file that much now lol

2024-07-12 03:24 UTC, doggogit commented on README.md
> +Full credits can be found in-game, [CREDITS.md,](https://github.com/FunkinCrew/Funkin) or [in the `credits.json` file](https://github.com/FunkinCrew/funkin.assets/blob/main/exclude/data/credits.json)
```suggestion
Full credits can be found in-game or in [CREDITS.md](https://github.com/FunkinCrew/Funkin).
```

2024-07-12 03:24 UTC, doggogit commented on docs/CREDITS.md
> +Full credits can be found in-game, or wherever the credits.json file is.
```suggestion

```

2024-07-12 03:31 UTC, doggogit commented
You forgot to edit the lines in the README, but other than that, this is a pretty solid PR

2024-07-12 03:32 UTC, doggogit approved these changes
Once the Twitter links for specific members get sorted out, I've got no problem having this PR merged!

2024-07-12 03:35 UTC, Hundrec commented on README.md
> +Full credits can be found in-game, [CREDITS.md,](https://github.com/FunkinCrew/Funkin) or [in the `credits.json` file](https://github.com/FunkinCrew/funkin.assets/blob/main/exclude/data/credits.json)
```suggestion
Full credits can be found in-game or in the [CREDITS.md](/docs/CREDITS.md) file.
```

2024-07-12 03:37 UTC, JVNpixels commented
> You forgot to edit the line in the README, but other than that, this is a pretty solid PR

Which line was it again? I think it's just fine.

2024-07-12 03:38 UTC, doggogit commented
> > You forgot to edit the line in the README, but other than that, this is a pretty solid PR
> 
> Which line was it again? I think it's just fine.

The one that you just fixed. It's good now!

2024-07-12 03:39 UTC, JVNpixels commented
:D

2024-07-12 03:40 UTC, Hundrec commented
I'd like to note that CREDITS.md appears to credit fewer people than credits.json does, so maybe we should keep credits.json easily accessible in the README

2024-07-12 03:41 UTC, JVNpixels commented
@Hundrec, yes that would be a good idea.

2024-07-12 03:44 UTC, doggogit commented
> I'd like to note that CREDITS.md appears to credit fewer people than credits.json does, so maybe we should keep credits.json easily accessible in the README     

Oh, didn't realize that, then sure, you can just put the line back in

2024-07-12 03:48 UTC, doggogit requested changes
Like this?

2024-07-12 03:48 UTC, doggogit commented on README.md
> +Full credits can be found in-game or in the [credits.json](https://github.com/FunkinCrew/funkin.assets/blob/main/exclude/data/credits.json) file or in the [CREDITS.md](/docs/CREDITS.md) file.
```suggestion
Simplified credits can be found in [CREDITS.md](/docs/CREDITS.md), while full credits can be found in-game or [in the `credits.json` file](https://github.com/FunkinCrew/funkin.assets/blob/main/exclude/data/credits.json).
```

2024-07-12 03:51 UTC, JVNpixels commented on README.md
> +Full credits can be found in-game or in the [credits.json](https://github.com/FunkinCrew/funkin.assets/blob/main/exclude/data/credits.json) file or in the [CREDITS.md](/docs/CREDITS.md) file.
Yes thank you!

2024-07-12 03:54 UTC, doggogit approved these changes

2024-07-12 05:09 UTC, Hundrec requested changes
I've compiled some Twitter handles (and personal websites if no Twitter) that I'm _fairly_ confident belong to the respective individuals

This is only for the Programming section, but I will add more as I find them!

2024-07-12 05:09 UTC, Hundrec commented on docs/CREDITS.md
> +- [EliteMasterEric](https://twitter.com/EliteMasterEric) - Programmer
```suggestion
- [EliteMasterEric](https://twitter.com/EliteMasterEric) - Programmer
- [fabs](https://twitter.com/fabsthefabs) - Programmer
```

2024-07-12 05:09 UTC, Hundrec commented on docs/CREDITS.md
> +- [Jenny Crowe](https://twitter.com/JennyCrowe) - Additional Programming
```suggestion
- [Jenny Crowe](https://twitter.com/jennyminer_biz) - Additional Programming
```

2024-07-12 05:09 UTC, Hundrec commented on docs/CREDITS.md
> +- [Ian Harrigan](https://twitter.com/IanHarrigan) - Additional Programming
```suggestion
- [Ian Harrigan](https://twitter.com/ianharrigan1982) - Additional Programming
```

2024-07-12 05:09 UTC, Hundrec commented on docs/CREDITS.md
> +- [Will Blanton](https://twitter.com/WillBlanton) - Additional Programming
```suggestion
- [Will Blanton](https://twitter.com/x01010111) - Additional Programming
```

2024-07-12 05:09 UTC, Hundrec commented on docs/CREDITS.md
> +- [Cheemsandfriends](https://twitter.com/Cheemsandfriends) - FlxAnimate
```suggestion
- [Cheemsandfriends](https://twitter.com/CheemsnFriendos) - FlxAnimate
```

2024-07-12 05:18 UTC, JVNpixels commented
@Hundrec, these changes should be added! Maybe next time I should think through thoroughly with things like these next time! 😅😅😅

2024-07-12 05:25 UTC, Hundrec requested changes
Here's another batch!

I think the rest of the links are fine, or are impossible to find without dev confirmation (beck)

2024-07-12 05:25 UTC, Hundrec commented on docs/CREDITS.md
> +- [Sade](https://twitter.com/Sade) - Cutscene Animation
```suggestion
- [Sade](https://twitter.com/sadewoo0) - Cutscene Animation
```

2024-07-12 05:25 UTC, Hundrec commented on docs/CREDITS.md
> +- [Topium](https://twitter.com/Topium) - Cutscene Animation
```suggestion
- [Topium](https://twitter.com/topium_) - Cutscene Animation
```

2024-07-12 05:25 UTC, Hundrec commented on docs/CREDITS.md
> +- [PennilessRagamuffin](https://twitter.com/PennilessRagamuffin) - Cutscene Animation
```suggestion
- [PennilessRagamuffin](https://twitter.com/matchragamuffin) - Cutscene Animation
```

2024-07-12 05:25 UTC, Hundrec commented on docs/CREDITS.md
> +- [BlairTheUnseriousGuy](https://twitter.com/BlairTheUnseriousGuy) - Cutscene Animation
```suggestion
- [BlairTheUnseriousGuy](https://twitter.com/unseriousguy) - Cutscene Animation
```

2024-07-12 05:25 UTC, Hundrec commented on docs/CREDITS.md
> +- [beck](https://twitter.com/beck) - Art, Cutscene Cleanup, Cutscene Background Art
```suggestion
- [beck](https://twitter.com/?????) - Art, Cutscene Cleanup, Cutscene Background Art, Merch Design
```

I've got nothing for beck.

2024-07-12 05:25 UTC, Hundrec commented on docs/CREDITS.md
> +- [SrPelo](https://twitter.com/SrPelo) - Voice of Spooky Kids
```suggestion
- [SrPelo](https://twitter.com/_srpelo_) - Voice of Spooky Kids
```

2024-07-12 05:26 UTC, Hundrec commented
> @Hundrec, these changes should be added! Maybe next time I should think through thoroughly with things like these next time! 😅😅😅

Don't worry about it, I'm glad you took the initiative to update the credits and make them more accessible!

2024-07-12 05:34 UTC, JVNpixels commented
Alright, everything should be just fine now! 👍

2024-07-12 05:40 UTC, JVNpixels commented
@Hundrec, I think this is good for approval, could you please review it?

2024-07-12 05:42 UTC, JVNpixels commented
I’m pretty sure everything should be good now, and next time I do something documentation related (which I probably wont), then I will organize it and clean it up better as well as making ideas like to split the credits into its own file and stuff like that.

2024-07-12 05:42 UTC, Hundrec commented
I think the structure and links look good now!

I'll approve this PR once we get official confirmation for beck's social media and verification for everyone else's links.

2024-07-19 19:04 UTC, JVNpixels commented
> I think the structure and links look good now!
> 
> I'll approve this PR once we get official confirmation for beck's social media and verification for everyone else's links.

I found beck’s social media! Although their account is mostly for adult audiences, but I looked at the official FNF developers twitter page and who they were following and I found beck.

2024-07-19 19:06 UTC, Hundrec commented
Nice sleuthing! Now we just need the devs' confirmation :)

2024-07-21 17:49 UTC, MAZ12211 commented
Just a suggestion, you might want to credit charters because fabs (along with spazkid) also charted a lot of erect remixes.

2024-10-08 18:13 UTC, ninjamuffin99 commented
I think we don't particularly need another credits related file to maintain and update. The JSON creds file is generally readable on web, and I don't think we particularly need links to socials for everyone in the credits, as it may not be their preference. If the people we work with ask for us to credit social medias, we will comply! 

So do appreciate the effort but I will close this PR!

2024-10-08 18:13 UTC, closed without merging

2024-10-08 23:18 UTC, JVNpixels commented
its ok it was like 2 months ago and hundrec did most of the commits