[ENHANCEMENT] Open PauseSubState on PlayState Focus Loss
FunkinCrew/Funkin pull request #3004
Opened 2024-07-11 02:47 UTC by CrusherNotDrip

This PR makes it so it opens the `PauseSubState` when the game loses focus on `PlayState`.

This is helpful in a scenario where the player unfocused the game along with having the preference **Auto Pause** disabled, it will pause the game helping save their current score, accuracy and misses.

Only thing is that this will not work if charting mode is enabled. (Probably because it has something to do with PlayState being a substate)

2024-07-11 07:47 UTC, EliteMasterEric commented
Isn't this supposed to be OFF if Auto-Pause is disabled? I'd imagine that if Auto-Pause is off, the user probably, you know, wouldn't want the game to automatically pause.

Also I'm confused as to why your code wouldn't work in charting mode, you can still pause the game in the playtest.

2024-07-11 10:01 UTC, CrusherNotDrip commented
> Isn't this supposed to be OFF if Auto-Pause is disabled? I'd imagine that if Auto-Pause is off, the user probably, you know, wouldn't want the game to automatically pause.

You know what fair enough but even with it being turned on, the game only freezes on focus loss so should I just make this go only with the auto pause preference ON then? or would this PR just be a no go?

> Also I'm confused as to why your code wouldn't work in charting mode, you can still pause the game in the playtest.

im confused too 😭😭😭

2024-07-29 01:43 UTC, Cartridge-Man commented
I feel like if this was changed to work only for auto pause, then this would work perfectly

2024-07-30 18:58 UTC, Cartridge-Man commented
lol nice

2025-01-22 18:04 UTC, AbnormalPoof commented
This PR appears to have merge conflicts. Please fix them!

2025-01-23 03:14 UTC, CrusherNotDrip commented
oop

2025-01-23 03:14 UTC, CrusherNotDrip commented
chat i might've messed up

2025-01-23 03:23 UTC, CrusherNotDrip commented
ok there we go

2025-03-20 14:26 UTC, TechnikTil requested changes
doesn’t account for having a cutscene playing, so cutscene options don’t show up

2025-03-20 18:18 UTC, CrusherNotDrip commented
> doesn’t account for having a cutscene playing, so cutscene options don’t show up

oh thank you sherlock holmes i didn't know such information

2025-03-21 14:52 UTC, TechnikTil commented
> The art of deduction
trues...

2025-04-05 03:49 UTC, Hundrec commented
Please fix up the merge conflicts!

2025-04-05 04:50 UTC, TechnikTil commented
crusher get off schedule I and fix ur pr

2025-04-05 05:24 UTC, CrusherNotDrip commented
man i really hope that works

2025-04-05 05:25 UTC, TechnikTil commented
that surprisingly worked😭

2025-04-05 06:07 UTC, Hundrec commented
All in a day's work

2025-04-05 06:41 UTC, CrusherNotDrip commented
speaking of a days work i got 1k in a day in schedule I

2025-04-05 19:31 UTC, TechnikTil commented
> speaking of a days work i got 1k in a day in schedule I

ok man

2025-04-06 04:31 UTC, Lasercar commented
> speaking of a days work i got 1k in a day in schedule I

Stop slacking off and do some actual day work

2025-07-25 23:18 UTC, CrusherNotDrip commented
Welp

2025-07-25 23:18 UTC, closed without merging