FIXES CHARACTER PATH ONLY CHECKING IN SHARED
FunkinCrew/Funkin pull request #3035
Opened 2024-07-16 09:52 UTC by 7oltan

so im trying to make it so it will load characters from a week dir but its not letting me so i checked and saw this was the problem so i fixed it :3

2024-07-16 10:36 UTC, moxie-coder commented
I don't think this is a good idea since I don't think it checks in shared by default

2024-07-16 14:20 UTC, anysad commented
why not just place character assets in `shared/images/characters`?

2024-07-16 14:23 UTC, anysad commented
> I don't think this is a good idea since I don't think it checks in shared by default

it doesn't check in `shared` by default, it initially checks in `preload`

2024-07-16 14:26 UTC, moxie-coder commented
> > I don't think this is a good idea since I don't think it checks in shared by default
> 
> it doesn't check in `shared` by default, it initially checks in `preload`

I know, that's kinda why I think this might cause issues

2024-07-16 17:11 UTC, 7oltan commented
> > > I don't think this is a good idea since I don't think it checks in shared by default
> > 
> > 
> > it doesn't check in `shared` by default, it initially checks in `preload`
> 
> I know, that's kinda why I think this might cause issues

why tho?

2024-07-16 17:12 UTC, 7oltan commented
> why not just place character assets in `shared/images/characters`?

i want to add the characters in a week type dir to save memory and just to make images look cleaner

2024-07-18 17:39 UTC, mayo78 commented
> > > I don't think this is a good idea since I don't think it checks in shared by default
> > 
> > 
> > it doesn't check in `shared` by default, it initially checks in `preload`
> 
> I know, that's kinda why I think this might cause issues

how would it be an issue? it checks first for preload, then for the level path, and then shared

2024-07-23 04:03 UTC, EliteMasterEric commented
Paths automatically checks which library has the file before using it, so this should be good.

I believe characters were originally IN the level folders before moving them out due to issues when characters were shared between levels.

2024-08-28 13:20 UTC, PurSnake requested changes

2024-08-28 13:20 UTC, PurSnake commented on source/funkin/play/character/AnimateAtlasCharacter.hx
> -    var sprite:FlxAtlasSprite = new FlxAtlasSprite(0, 0, Paths.animateAtlas(_data.assetPath, 'shared'));
For this move you should rewrite Paths atlas thing since it takes the atlas without checking the shared library

2024-08-28 13:26 UTC, PurSnake approved these changes

2024-09-16 22:10 UTC, merged

2024-12-16 09:50 UTC, 7oltan commented
@EliteMasterEric so this may or may not have broken how animate atlas characters work, since paths for animate atlases uses getLib path and now that's it's null it ONLY checks in preload, and before that it only checked in shared, you should make it so the paths.animateAtlas takes the path and checks for its animate json file by normal getPath and then make it go back a few to the folder

2024-12-16 15:44 UTC, EliteMasterEric commented
> @EliteMasterEric so this may or may not have broken how animate atlas characters work, since paths for animate atlases uses getLib path and now that's it's null it ONLY checks in preload, and before that it only checked in shared, you should make it so the paths.animateAtlas takes the path and checks for its animate json file by normal getPath and then make it go back a few to the folder

I don't understand what you mean, if this breaks things then Blazin' would be unplayable.

2024-12-19 11:54 UTC, 7oltan commented
> > @EliteMasterEric so this may or may not have broken how animate atlas characters work, since paths for animate atlases uses getLib path and now that's it's null it ONLY checks in preload, and before that it only checked in shared, you should make it so the paths.animateAtlas takes the path and checks for its animate json file by normal getPath and then make it go back a few to the folder
> 
> 
> 
> I don't understand what you mean, if this breaks things then Blazin' would be unplayable.

The characters in blazin' put "shared:" in the start of the path; but mods that don't before it would work for them and now their characters are broken ![image](https://github.com/user-attachments/assets/4269f4fb-576a-4251-a096-e8a460bb0b61)

2024-12-23 01:53 UTC, mayo78 commented
kinda not a problem though? in normal flixel projects you already get assets from libraries in that way