automatic offset flipping merge
FunkinCrew/Funkin pull request #3543
Opened 2024-10-03 00:15 UTC by cyn0x8

## Briefly describe the issue(s) fixed.
offset fix for #3539 
currently planning to fix offsets for rotated sprites as well, but i cant test anything yet because every state with a character in it seems to crash in this branch atm lol

2024-10-03 12:59 UTC, lemz1 requested changes

2024-10-03 12:59 UTC, lemz1 commented on source/funkin/play/stage/Bopper.hx
> +    // adjustedOffsets = adjustedOffsets.pivotDegrees(FlxPoint.weak(0, 0), this.angle);
this seems to work for the angle stuff.
```haxe
adjustedOffsets.degrees += this.angle; // this is just a shorthand for what you have written before
```

2024-10-03 16:18 UTC, EliteMasterEric commented
Base branch has been updated to include working submodules.

Also, your changes do NOT fix Tankman's flipped animations regardless of configuration. The feature needs to work on any characters whose offsets are correct right now, otherwise it will create a bunch of work for us (manually reconfiguring offsets) as well as a bunch of work for mod creators (who will have to fix their character offsets).

Try testing characters where `"flipX": true` is set.

2024-10-04 02:09 UTC, cyn0x8 commented
i took some notes
```
player sprite   with offsets intended for player side   on player side
data flipX should be true
flipX      is false (stage flipX != data flipX -> true  != true)
offsets    should not be flipped (already aligned)

player sprite   with offsets intended for player side   on opponent side
data flipX should be true
flipX      is true  (stage flipX != data flipX -> false != true)
offsets    should be flipped if flipXOffsets is true

player sprite   with offsets intended for opponent side on player side
data flipX should be true
flipX      is false (stage flipX != data flipX -> true  != true)
offsets    should be flipped if flipXOffsets is true

player sprite   with offsets intended for opponent side on opponent side
data flipX should be true
flipX      is true  (stage flipX != data flipX -> false != true)
offsets    should not be flipped (already aligned)

opponent sprite with offsets intended for player side   on player side
data flipX should be false
flipX      is true  (stage flipX != data flipX -> true  != false)
offsets    should not be flipped (already aligned)

opponent sprite with offsets intended for player side   on opponent side
data flipX should be false
flipX      is false (stage flipX != data flipX -> false != false)
offsets    should be flipped if flipXOffsets is true

opponent sprite with offsets intended for opponent side on player side
data flipX should be false
flipX      is true  (stage flipX != data flipX -> true  != false)
offsets    should be flipped if flipXOffsets is true

opponent sprite with offsets intended for opponent side on opponent side
data flipX should be false
flipX      is false (stage flipX != data flipX -> false != false)
offsets    should not be flipped (already aligned)
```

whether the offsets are intended for the player or opponent side is arbitrary and this affects when the offsets should be flipped, so im rewriting the properties to reflect that

see updated pr description

2025-01-26 07:57 UTC, cyn0x8 commented
does this pr still need revision? and if so what do i need to change?

2025-04-03 19:20 UTC, cyn0x8 commented
forgot to make rotation relative to `origin` oops

2026-08-29 12:50 UTC, Hundrec commented
Closing this as stale.
Is this PR revivable for the new branch `preview/public-playtest`?
I like the concept of this feature

2026-08-29 12:50 UTC, closed without merging