Audio visual offset start
FunkinCrew/Funkin pull request #3732
Opened 2024-10-19 08:33 UTC by xenkap

Starting the song previously utilized combinedOffset to offset where in the song the instrumental starts in.
This is no longer the case, instead using instrumentalOffset for starting.

The Conductor and Countdown classes have been altered to reflect this behavior.

function startSong also no longer uses resyncVocals().
It was kind of pointless being there, and needing to play the instrumental before calling it makes the audio double up sometimes and it sounds awful

## Does this PR close any issues? If so, link them below.
[TBA, but quick searches about offset don't show much]
## Briefly describe the issue(s) fixed.
Audio used to skip forward when negative values of Audio/Visual Offset were present. This is now fixed, along with ugly audio doubling behavior on start.
## Include any relevant screenshots or videos.
[TBA]

2024-10-19 08:35 UTC, xenkap commented
Currently a weird awkward pause after the countdown before the song plays. Currently investigating

2024-10-19 08:51 UTC, xenkap commented
okay all good :yippe:

2024-10-19 09:08 UTC, xenkap commented
added footage :D

2024-10-30 05:47 UTC, cyn0x8 approved these changes

2024-10-30 12:09 UTC, xenkap commented on source/funkin/Conductor.hx
> +      this.songPosition = Math.min(currentLength, Math.max(Math.min(this.combinedOffset, 0), songPos));
i forgot FlxMath.bound existed 😭 thank you !!

2024-11-06 16:16 UTC, xenkap commented
Not sure if this is an issue on my end specifically, but after switching to Linux I've found myself using positive visual offset.
It seems to have an awkward pause at the end of the countdown like it did before-- can someone else see if this happens to them too?

Also, squashing these commits. Kinda messy

2025-01-21 23:50 UTC, NotHyper-474 commented
https://github.com/FunkinCrew/Funkin/issues/3039 should be linked to this

2025-01-22 04:10 UTC, Squiddu commented
don't know entirely if this fixes everything recorded in the issue, but thank GOD someone else noticed something was wrong, thank you i am free

2025-02-19 23:57 UTC, JackXson-Real approved these changes

2025-02-19 23:58 UTC, JackXson-Real commented
Just did some testing, and it works flawlessly! Can't wait for this one to be merged. It's been a pain in the ass dealing with this issue.

2025-02-20 01:45 UTC, Hundrec approved these changes
Tested this and it does resolve the skipping on start!
Offsets are still far from playable for me, but this makes it a little better :)

2025-03-11 21:23 UTC, EliteMasterEric requested changes
Just tested this out on Eggnog Erect like in the example, the audio skip is resolved but I can't hit Boyfriend's first down note! It just doesn't respond to inputs at all.

2025-03-11 21:34 UTC, Hundrec commented
> Just tested this out on Eggnog Erect like in the example, the audio skip is resolved but I can't hit Boyfriend's first down note! It just doesn't respond to inputs at all.

Yeah, I encountered this issue consistently when I tested it a few weeks ago
After some discussion with @JackXson-Real, we decided this PR  fixed the issue as promised, though it leaves notes at the beginning of the song impossible to hit.

2025-03-11 21:54 UTC, JackXson-Real commented
> Just tested this out on Eggnog Erect like in the example, the audio skip is resolved but I can't hit Boyfriend's first down note! It just doesn't respond to inputs at all.

This PR fixes the issue with the audio skipping exclusively. The issue with high input offset on Eggnog Erect exists on the develop branch as well, so it was not an issue introduced by this PR. I believe this should be merged as is and then hopefully someone can make a PR that fixes that issue.

2025-03-30 12:27 UTC, xenkap commented
Oh! This actually got looked at. I kind of went inactive a while after I made these PRs...
It's probably already fixed internally in the update coming in probably less than a day, but I'm gonna see what I can do anyway

2025-03-30 13:44 UTC, xenkap commented
> > Just tested this out on Eggnog Erect like in the example, the audio skip is resolved but I can't hit Boyfriend's first down note! It just doesn't respond to inputs at all.
> 
> Yeah, I encountered this issue consistently when I tested it a few weeks ago After some discussion with @JackXson-Real, we decided this PR fixed the issue as promised, though it leaves notes at the beginning of the song impossible to hit.

Couldn't replicate the described problem - tried higher, lower, exactly 100ms offsets.
Disabled all note-related mods to be sure, 0 input offset, made sure I was on the right branch.
I could hit the Eggnog Erect note just fine -- maybe some commit upstream fixed it while I merged????

It seems to be working fine on my machine, anyhow, so if the issue persists, do respond with your offset configs
I have a feeling that it might be unrelated to this PR and instead related to _Input_ Offsets, which I've fixed in a separate PR

2025-03-30 19:59 UTC, JackXson-Real commented
> > > Just tested this out on Eggnog Erect like in the example, the audio skip is resolved but I can't hit Boyfriend's first down note! It just doesn't respond to inputs at all.
> > 
> > 
> > Yeah, I encountered this issue consistently when I tested it a few weeks ago After some discussion with @JackXson-Real, we decided this PR fixed the issue as promised, though it leaves notes at the beginning of the song impossible to hit.
> 
> Couldn't replicate the described problem - tried higher, lower, exactly 100ms offsets. Disabled all note-related mods to be sure, 0 input offset, made sure I was on the right branch. I could hit the Eggnog Erect note just fine -- maybe some commit upstream fixed it while I merged????
> 
> It seems to be working fine on my machine, anyhow, so if the issue persists, do respond with your offset configs I have a feeling that it might be unrelated to this PR and instead related to _Input_ Offsets, which I've fixed in a [separate PR](https://github.com/FunkinCrew/Funkin/pull/3708/)

We got the bug on 200ms offset.

2025-03-31 02:33 UTC, xenkap commented
> We got the bug on 200ms offset.

Still can't replicate it...
[Trying to attach a video, but can't atm]

Are you sure you didn't set _input offset_ instead while testing?
Because I tried that and had outcomes that match the description

2025-04-01 02:56 UTC, xenkap commented
> I tested the fixes provided here as well as in #3708 along with managing to replicate the issue. Here's what -200 visual offset and 200 input offset looks like right now, both in 0.5.3 and 0.6.0 (clip is from 0.5.3 but I tested it on 0.6.0 as well and it looked the exact same -- note just flies by and hit windows seem unplayable):
> ...

:yippe:
So it _is_ just the input offset causing it! This PR doesn't touch that [not its job] but the other PR (https://github.com/FunkinCrew/Funkin/pull/3708) fixes it.
The reason this happens is because the input offset is shifting the rating windows but not the hit windows. It's wack lol
Please review again 🥺

2025-05-01 07:20 UTC, xenkap commented
Rebased and cleaned up the PR's commit history, Hoping for a re-review considering it seems like PRs are currently being checked outright now :pray:

2025-05-01 10:53 UTC, Hundrec commented
Feel free to re-request reviews to get our attention!

2025-05-01 14:51 UTC, JackXson-Real commented
Best PR is back

2025-05-01 16:20 UTC, NotHyper-474 commented on source/funkin/play/PlayState.hx
> +    var pre:Float = (Conductor.instance.beatLengthMs * -5) + startTimestamp + Conductor.instance.combinedOffset;
This is a bit redundant since `Conductor::update` has `applyOffsets` which is `True...` by default.

2025-05-01 19:12 UTC, JackXson-Real approved these changes
I love you bro. @Kade-github please review this and get it into 0.6.4, this is needed especially since 0.6.0 because there are lots more songs that start immediately.

2025-05-01 19:58 UTC, EliteMasterEric commented
For this one, aside from general testing to make sure this doesn't break anything, how does this work when playing Senpai BF mix with the Pico alt instrumental? Currently that one has an unresolved bug where it skips forward slightly and this might fix that.

2025-05-01 20:04 UTC, JackXson-Real commented
> For this one, aside from general testing to make sure this doesn't break anything, how does this work when playing Senpai BF mix with the Pico alt instrumental? Currently that one has an unresolved bug where it skips forward slightly and this might fix that.

It seems to play the exact same as it would when playing the Pico version, so it is synced properly. Are you talking about the half second intro that Senpai Pico has in the OST version, but is not there in-game?

2025-05-01 20:06 UTC, Hundrec commented
He must've meant Roses.

2025-05-01 20:12 UTC, JackXson-Real commented
@EliteMasterEric Here is a video showing the behavior of Roses BF with alt inst. It doesn't really seem to fix that issue, but just makes it happen slightly different (it plays the full intro instead, but vocals are still delayed to work with the song)

https://github.com/user-attachments/assets/f99523d9-a343-4f89-a4e4-9325c5b6f97e

2025-05-02 05:23 UTC, xenkap commented on source/funkin/play/PlayState.hx
> +    var pre:Float = (Conductor.instance.beatLengthMs * -5) + startTimestamp + Conductor.instance.combinedOffset;
Ah, true! Didn't catch that, thanks

2025-05-02 05:26 UTC, xenkap commented
> @EliteMasterEric Here is a video showing the behavior of Roses BF with alt inst. It doesn't really seem to fix that issue, but just makes it happen slightly different (it plays the full intro instead, but vocals are still delayed to work with the song)

Oh! Haven't seen this issue. Going to see if I can do anything about this, but what is the intended behavior?
Should it skip the instrumental's intro or should it wait like my PR did? :3c

2025-05-02 05:29 UTC, JackXson-Real commented
> > @EliteMasterEric Here is a video showing the behavior of Roses BF with alt inst. It doesn't really seem to fix that issue, but just makes it happen slightly different (it plays the full intro instead, but vocals are still delayed to work with the song)
> 
> Oh! Haven't seen this issue. Going to see if I can do anything about this, but what is the intended behavior? Should it skip the instrumental's intro or should it wait like my PR did? :3c

Me and Hundrec believe it works better if the full instrumental plays. The main issue with it currently is the initial audio skip at the beginning, and restarting the song makes senpai’s first set of notes not appear.

2025-05-02 05:31 UTC, xenkap commented
> Me and Hundrec believe it works better if the full instrumental plays. The main issue with it currently is the initial audio skip at the beginning, and restarting the song makes senpai’s first set of notes not appear.

![image](https://github.com/user-attachments/assets/7630b886-d2ec-4026-b9bd-7fa5e2e88e1b)
Found it, lol. At least I think so, and adding the offsets here should fix it! Going to test...

2025-05-02 07:01 UTC, xenkap commented
![image](https://github.com/user-attachments/assets/d0aa99e2-ed05-4481-bb3e-d3df7865d4f5)
OK, found the actual cause! Since this check is based on the song's position (the instrumental) and disregards the vocal offset, it erroneously concludes that the vocals are "too far in the past" to load.

HOWEVER!! This makes things complicated, and makes me ask: why are Alt Inst/Vocal offsets specified per-character? Why are they separate from the altInstrumental offset??
And, most importantly, how do we account for that here? :sob:

2025-05-02 07:57 UTC, EliteMasterEric commented
Setting offsets in the instrumental and offsets separately is used in the case where the vocals aren't properly synced to the instrumental, so you don't need to wait for the musician to re-export

Also, for the record, the correct behavior is that when Roses is played with Pico's instrumental, the full intro should play and the chart and vocals should start at the appropriate time as configured by the vocal offset. Some versions of the game start Roses Pico inst 4 seconds into the song, which a bug.

2025-05-02 09:28 UTC, xenkap commented
> After some debugging... it appears # 4875 fixes the notes disappearing! I'll probably post some explanation there or on the issue tracking it (#4839) so I don't clutter this PR's comments further :]c
@Hundrec Should this PR be considered as fixing the same issue? As it seems to fix the song skipping ahead as well

2025-05-02 09:35 UTC, Hundrec commented
I'll have to test Roses Pico Inst with this PR, I'll let you know how it goes!

2025-05-02 11:56 UTC, Hundrec commented
So close! It plays a split second of the original behavior before resetting to the beginning.

https://github.com/user-attachments/assets/ee0a9b12-bd1c-432f-9315-0a5981b7d7f6

2025-05-03 03:45 UTC, xenkap commented on source/funkin/play/PlayState.hx
> +        FlxG.sound.music.time = startTimestamp - Conductor.instance.instrumentalOffset;
Yeah, not really sure what's going on with instrumentalOffset -- is it supposed to skip the audio forwards, or not?
I'll just assume that it shouldn't and this was scrapped behavior -- but after removing the lines involved, the vocals play weirdly offset!

Honestly might just slap resyncVocals() back into startSong(). It'd work, but it's kind of a band-aid fix...

2025-05-03 03:48 UTC, xenkap commented on source/funkin/play/PlayState.hx
> +        FlxG.sound.music.time = startTimestamp - Conductor.instance.instrumentalOffset;
> ... and this was scrapped behavior -- but after removing the lines involved, the vocals play weirdly offset!
oh snap that was my offset! okay, figured it out

2025-05-03 04:22 UTC, xenkap commented
![image](https://github.com/user-attachments/assets/42f5179d-efdc-466b-bdd5-1de5a05c9ded)
Now just why would you do that? :sob:

2025-05-03 04:34 UTC, JackXson-Real commented
@xenkap please update this to the 0.6.4 release so I can play it with these fixes cause now I'm too used to them 😭

2025-05-03 04:48 UTC, xenkap commented
> @xenkap please update this to the 0.6.4 release so I can play it with these fixes cause now I'm too used to them 😭

wait 0.6.4 dropped already??? :sob:

2025-05-03 04:52 UTC, xenkap commented
0.6.4 rebased! yeaaah !!

2025-05-29 04:55 UTC, Kade-github commented
ill look at this tomorrow :D

2025-05-29 23:11 UTC, JackXson-Real commented
> ill look at this tomorrow :D

Thank you kade please get this into 0.7.0 cause I can’t play without it now 🙏

2025-06-04 18:11 UTC, Kade-github approved these changes
works, defn going to need ur other pr for it to be perfect though. Along with me eventually fixing the offset menu because it isn't too great.

2025-06-04 18:12 UTC, Kade-github commented
sorry for the delay tho, I was busy :D

2025-06-04 18:13 UTC, JackXson-Real commented
We won

2025-06-04 21:05 UTC, EliteMasterEric approved these changes

2025-06-17 00:48 UTC, merged

2025-06-17 00:48 UTC, AbnormalPoof commented
i forgot to merge this after resolving the conflicts lmao