[ENHANCEMENT] Faster Game Over Mashing (and some cherries on top)
FunkinCrew/Funkin pull request #3826
Opened 2024-11-03 02:20 UTC by TechnikTil

## About:
This PR adds the ability to skip the confirm sound in GameOverSubState, making it even faster to restart a song. Also, this PR prevents sound effects from colliding into each other, and organizes a little bit.

## Video:
[yt video cuz its over 10MB](https://youtu.be/2Taq-ll05c8)

2024-11-03 02:28 UTC, Hundrec commented
Ooh, this would address a lot of existing issues!
Can we see a video?

2024-11-03 02:33 UTC, TechnikTil commented
> Ooh, this would address a lot of existing issues! Can we see a video?

yt video

2024-11-03 02:38 UTC, charlesisfeline approved these changes

2024-11-03 02:48 UTC, Hundrec commented
Oh whoops, missed the link
This video is actually hilarious and gets the point across, love it!

2024-11-03 02:49 UTC, Hundrec approved these changes

2024-11-03 04:26 UTC, CrusherNotDrip commented
> [yt video cuz its over 10MB](https://youtu.be/2Taq-ll05c8)

[https://8mb.video/](https://8mb.video/) unless u dont want it to look a bit poo poo

2024-11-03 04:27 UTC, CrusherNotDrip approved these changes

2024-11-03 04:27 UTC, CrusherNotDrip commented
also i found this pr because of u posting this on youtube :sob:

2024-11-03 04:29 UTC, TechnikTil commented
> also i found this pr because of u posting this on youtube :sob:

lmao

2024-11-05 17:46 UTC, TechnikTil commented
ok, i found a bug

if you spam enough in week 6, the pixel fade shader says fuck you and breaks

gonna go fix that rq

2024-11-06 02:12 UTC, TechnikTil commented
> ok, i found a bug
> 
> if you spam enough in week 6, the pixel fade shader says fuck you and breaks
> 
> gonna go fix that rq

gonna make that a different pr hahahahahpahljifjnbdasjhklfg adshjikubgvads jghkfgasd hgvfkdsghj kmf djghksafkhj gdsf

2024-11-06 02:53 UTC, CrusherNotDrip commented
> > ok, i found a bug
> > if you spam enough in week 6, the pixel fade shader says fuck you and breaks
> > gonna go fix that rq
> 
> gonna make that a different pr hahahahahpahljifjnbdasjhklfg adshjikubgvads jghkfgasd hgvfkdsghj kmf djghksafkhj gdsf

BOOOO L PR 0/10 I HATE PEOPLE NAMED TECHNIKTIL BOOOO

2024-12-14 23:47 UTC, TechnikTil commented
there we go (sorry)

2025-02-20 22:02 UTC, Hundrec requested changes
I've finally gotten around to testing this and quickly encountered a bug
I'm not sure how often this would happen, but I couldn't make it happen on command.

Just wanted to let you know!


https://github.com/user-attachments/assets/016d0543-762a-497c-b43d-159421134a12

2025-02-20 22:24 UTC, charlesisfeline commented
> I've finally gotten around to testing this and quickly encountered a bug I'm not sure how often this would happen, but I couldn't make it happen on command.
> 
> Just wanted to let you know!
> 
>  gameover.mash.mp4

stopping the inst works half of the time. apparently...

2025-02-20 22:29 UTC, TechnikTil commented
> I've finally gotten around to testing this and quickly encountered a bug
> 
> I'm not sure how often this would happen, but I couldn't make it happen on command.
> 
> 
> 
> Just wanted to let you know!
> 
> 
> 
> 
> 
> https://github.com/user-attachments/assets/016d0543-762a-497c-b43d-159421134a12
> 
> 
> 
> 

oop
ill go push a fix in a few, currently just got out of school

2025-02-20 22:38 UTC, JackXson-Real commented
> > I've finally gotten around to testing this and quickly encountered a bug
> > I'm not sure how often this would happen, but I couldn't make it happen on command.
> > Just wanted to let you know!
> > 
> >   
> >     
> >     
> > 
> >     gameover.mash.mp4
> 
> oop ill go push a fix in a few, currently just got out of school

I got the issue too. It seems to happen when you restart on the exact same frame the song starts, so it's basically a frame perfect input you have to do. Pretty fun to mess around with tho

2025-02-20 22:50 UTC, JackXson-Real commented
Darnell schizo moment

https://github.com/user-attachments/assets/fd76c43d-7979-4d3f-9f8b-d91a906bf8a9

2025-02-20 22:54 UTC, JackXson-Real commented
No way I just got the rare death screen while testing lmao
![screenshot-2025-02-20-17-53-25](https://github.com/user-attachments/assets/1c1653d9-e2d7-43d3-9a12-2febfc27a71a)

2025-02-20 22:56 UTC, Hundrec commented
I didn't even know the rare death screen was implemented, crazy!

2025-02-20 23:18 UTC, AbnormalPoof approved these changes
Works

2025-02-22 02:31 UTC, EliteMasterEric commented
I should ask what the team's opinions on this are.

Have all the issues with it been resolved? Will mark as `needs revision` until they are

2025-02-22 02:32 UTC, JackXson-Real commented
> I should ask what the team's opinions on this are.
> 
> Have all the issues with it been resolved? Will mark as `needs revision` until they are

I think they still have yet to fix the issue reported by Hundrec.

2025-02-22 08:35 UTC, TechnikTil commented
> I should ask what the team's opinions on this are.
> 
> Have all the issues with it been resolved? Will mark as `needs revision` until they are

need to fix the one that hundrec reported, then it should be ready to go

I think it does this cuz of FlxG.sound.music not initializing correctly, will do it as soon as I can

2025-02-23 05:21 UTC, TechnikTil commented
alr i think this should do it
a literal 1 line change

2025-02-23 19:08 UTC, JackXson-Real commented
> alr i think this should do it a literal 1 line change

Will test it and let you know. If it is fixed, I will approve it.

2025-02-23 19:18 UTC, JackXson-Real commented
Looks like it still exists. The changes you made didn't make it any less common either since I got it first try.

https://github.com/user-attachments/assets/512e9cc1-ee1c-461e-89d5-88ba55e8e04a

2025-02-23 19:30 UTC, JackXson-Real commented
Heres an extra video to show exactly how to get it to happen:

https://github.com/user-attachments/assets/dd9d19aa-b933-4484-abdb-2438051ebf3d

2025-02-24 22:49 UTC, JackXson-Real requested changes
Forgot to do this. Maybe make it so that you can’t game over right when the song starts? I’m not sure if that would work since I’m not a programmer, but that’s my suggestion.

2025-02-25 01:23 UTC, TechnikTil commented
sure why not

2025-03-15 01:59 UTC, JackXson-Real commented
> sure why not

Yo you alive?

2025-03-16 00:51 UTC, TechnikTil commented
i completely forgot to push 😭

2025-03-16 00:52 UTC, JackXson-Real commented
> i completely forgot to push 😭

You’re good lol, I will make sure to test this when I get back to my PC tomorrow.

2025-03-16 00:54 UTC, TechnikTil commented
thanks

2025-03-16 22:25 UTC, JackXson-Real approved these changes
The fix works perfect.

2025-03-17 04:14 UTC, Hundrec commented
Disabling gameover during the countdown certainly does make this bug harder to reproduce, but it's not impossible!
I've gotten it twice by spamming R and Enter, but only in about a hundred attempts.

I won't approve this due to the bug remaining, but this is fine to merge.

https://github.com/user-attachments/assets/382a6ae9-6e9c-40b7-8d84-da333aa57002

2025-03-22 05:52 UTC, Hundrec commented
Okay, just figured out how to replicate the bug.
Apparently if you spam enter at the same time as spamming R, you might bug out the pause screen and keep the music playing.
This can layer infinitely until the first layer ends, transitioning you to the Results screen.
Maybe you can disable pause inputs or something? No idea

2025-03-22 15:05 UTC, TechnikTil commented
> Okay, just figured out how to replicate the bug. Apparently if you spam enter at the same time as spamming R, you might bug out the pause screen and keep the music playing. This can layer infinitely until the first layer ends, transitioning you to the Results screen. Maybe you can disable pause inputs or something? No idea

This is very helpful, thanks!

2025-03-23 00:06 UTC, TechnikTil commented
i wonder if this has to do with the recycle pool in some way...

2025-03-23 00:21 UTC, TechnikTil commented
could everyone who can get the bug to occur try again? i have tried for about an hour and cant get it to happen

2025-03-23 02:08 UTC, TechnikTil commented
forgot i could do that, thanks abnormalpoof!

2025-03-23 02:27 UTC, Hundrec commented
Can't build the game. Is this my issue or the code's?

![image](https://github.com/user-attachments/assets/94000a2f-b035-4a07-9273-264477b52946)

2025-03-23 02:35 UTC, TechnikTil commented
oh my god
i forgot to save when i tested 😭

2025-03-23 02:44 UTC, Hundrec commented
Got the bug first try :(

https://github.com/user-attachments/assets/ff6562ec-c35d-4c06-a282-bc936ff3848d

2025-03-23 02:51 UTC, Hundrec commented
Just got the bug to happen on Base 0.5.3 as well.

Looks like your PR changes just make it easier to get the bug, not that it introduces it.

I think the PR should be good then!

https://github.com/user-attachments/assets/3e09b671-b96d-4c4c-9235-0e84cbc8ac89

2025-03-23 02:51 UTC, Hundrec approved these changes

2025-03-23 03:01 UTC, TechnikTil commented
should probably make an issue for that then

2025-03-23 03:01 UTC, TechnikTil commented
oop

2025-03-23 21:53 UTC, AbnormalPoof approved these changes
Works

2025-03-23 23:45 UTC, JackXson-Real approved these changes

2025-03-24 00:30 UTC, CrusherNotDrip approved these changes

2025-10-15 01:19 UTC, JackXson-Real approved these changes
Amazing

2026-01-14 21:59 UTC, CrusherNotDrip approved these changes

2026-02-02 18:04 UTC, TechnikTil commented
this is the closest thing im gonna get to a child

so close that i forgot it's birthday :(

2026-03-02 21:04 UTC, Kade-github approved these changes
fade in from black is a bit weird, but I think its fine.

2026-08-20 02:33 UTC, merged

2026-08-20 18:47 UTC, TechnikTil commented
🥹