[BUGFIX] Fix the `Random` Button in FreeplayState not being able to switch to Erect/Nightmare songs
FunkinCrew/Funkin pull request #3838
Opened 2024-11-06 21:49 UTC by KoloInDaCrib

## Does this PR close any issues? If so, link them below.
[3661](https://github.com/FunkinCrew/Funkin/issues/3661) [3762](https://github.com/FunkinCrew/Funkin/issues/3762)

## Briefly describe the issue(s) fixed.
Up until this point, the Freeplay Menu's `Random` button was only able to cycle to default difficulties (easy, normal, hard). This PR makes it so that it checks for all the songs loaded, makes an array for all the available difficulties per character, and goes through a for-loop to fill it up. That way it also accounts for Pico not having Erect/Nightmare songs and doesn't switch to those difficulties.

## Include any relevant screenshots or videos.
https://github.com/user-attachments/assets/d137f910-4789-41d7-9c1a-4eab27226b47

2025-01-17 20:02 UTC, EliteMasterEric requested changes

2025-01-17 20:02 UTC, EliteMasterEric commented on source/funkin/ui/freeplay/FreeplayState.hx
> +    for (song in songs)
I'd recommend moving this chunk of code to the SongRegistry and calling `allDifficulties = SongRegistry.instance.listAllDifficulties()`

2025-02-18 12:28 UTC, KoloInDaCrib commented
Reminder that the requested changes have been completed and this PR may be merged, if there are no further critiques

2025-02-20 02:55 UTC, JackXson-Real commented
Works good for the most part. Only problem is that when switching to erect mode, the songs don't have "erect" added onto their names until you hover over them, or if you switch to Nightmare mode.

2025-02-20 06:45 UTC, KoloInDaCrib commented
> Works good for the most part. Only problem is that when switching to erect mode, the songs don't have "erect" added onto their names until you hover over them, or if you switch to Nightmare mode.

Fixed, just had to delete a line

2025-02-20 23:26 UTC, AbnormalPoof approved these changes
Works

2025-04-09 18:11 UTC, Michu0204 commented
isnt this already fixed in 0.6.2

2025-04-09 18:12 UTC, NotHyper-474 commented
> isnt this already fixed in 0.6.2

it was merged internally

2025-05-02 00:16 UTC, merged