[ENHANCEMENT]: Miss Sound Preference
FunkinCrew/Funkin pull request #3869
Opened 2024-11-16 22:20 UTC by JVNpixels

This adds a miss sound preference to the game as for some people it can get annoying, so you can either turn it on or off.
![image](https://github.com/user-attachments/assets/6ab30cdb-170e-4d90-be09-2e09938f54dc)
I don't have an ingame version right now because the game isn't compiling, but I do know how to make an option without needing the game to compile.

2024-11-18 13:45 UTC, mcagabe19 approved these changes

2025-01-18 00:31 UTC, JVNpixels commented
> Looks like this PR needs an update/rebase

EliteMasterEric, I have rebased it now. Please review as soon as possible!

2025-01-18 01:29 UTC, charlesisfeline commented
> EliteMasterEric, I have rebased it now. Please review as soon as possible!

u just put it back to the main branch tho smh

2025-01-18 01:29 UTC, charlesisfeline commented
it did kinda help a bit tho

2025-01-18 02:01 UTC, AbnormalPoof commented
@JVNpixels This PR needs to be rebased for the `develop` branch to fix the merge conflicts. Non-documentation PRs generally are pushed to `develop`.

2025-01-18 02:12 UTC, NotHyper-474 requested changes

2025-01-18 02:12 UTC, NotHyper-474 commented on source/funkin/save/Save.hx
> +          playMissSound: false,
Isn't this supposed to be `true` instead?

2025-01-18 05:32 UTC, JVNpixels commented
Sorry, I am confused, where do I rebase this to?

2025-01-18 05:36 UTC, charlesisfeline commented
> Sorry, I am confused, where do I rebase this to?

`develop`

2025-01-18 05:39 UTC, JVNpixels commented
Why do we need to rebase? Wasn’t it already at develop? I don’t know the exact reason for it.. 😅

2025-01-18 15:24 UTC, NotHyper-474 approved these changes

2025-01-22 18:10 UTC, AbnormalPoof commented
This PR appears to have merge conflicts. Please fix them!

2025-01-25 00:25 UTC, Hundrec commented
This should be based on develop.

2025-01-25 22:00 UTC, JVNpixels commented
how do i get rid of these commits?

2025-01-25 22:36 UTC, NotHyper-474 commented
You can do what's called a rebase, but it's not the same as the base changing you do through the website.

2025-01-26 00:39 UTC, JVNpixels commented
> You can do what's called a rebase, but it's not the same as the base changing you do through the website.

i think i’ll just make a new P.R

2025-01-26 00:39 UTC, closed without merging

2025-01-28 20:49 UTC, JVNpixels commented
Wait just a question, this never happened before when I originally made the story mode P.R, why is this happening now? For the new pull request, where should I fork it from?

2025-01-28 20:55 UTC, AbnormalPoof commented
You based this pull request on `main`. Eric changed the base branch to `develop` which caused the extra commits to appear.

Generally, code-related pull requests (enhancement, bug fixes, optimizations, etc.) need to be based on `develop`. Documentation-related things (changes to GitHub files, files in docs/) need to be based on `main`.

2025-01-28 21:59 UTC, EliteMasterEric commented
Really wish there was an option for a default PR branch to help avoid issues like this.