Create CI
FunkinCrew/Funkin pull request #723
Opened 2021-04-07 12:47 UTC by regulad

An idea I had for testing commits and pull requests before marking them safe to merge. Most bigger projects implement some sort of CI with artifacts, who why not ninjamuffin9/Funkin?

You might need to change references made to me, like line 70.

2021-04-07 12:49 UTC, regulad commented
Tested, works.

2021-04-07 14:57 UTC, VoltrexMaster approved these changes
👍

2021-04-07 15:41 UTC, actuallyasmartname approved these changes
good

2021-04-07 15:57 UTC, Two-Ai commented
nice!
you might want to add Newgrounds and Switch build targets as well (see the build files in `art/build-*.bat`)

2021-04-07 23:04 UTC, regulad commented
> 
> 
> nice!
> you might want to add Newgrounds and Switch build targets as well (see the build files in `art/build-*.bat`)

Can't do switch since it requires copyrighted libraries. Newgrounds is just HTML5 with some extra stuff.
A CI is for checking the validity of code, as a side effect providing artifacts.

2021-04-07 23:21 UTC, Two-Ai approved these changes
ah, good point on the Switch stuff
I'd still suggest a Newgrounds build target to make sure the code is valid with and without `ng` defined, since some code is gated off with `#if ng` blocks. That said, it's relatively low impact so it's fine without.

2021-04-08 17:39 UTC, aflacc commented
im sorry **switch**???

2021-04-09 09:55 UTC, hdboye approved these changes
is gud

2021-04-13 17:57 UTC, aflacc commented
what is cl

2021-04-13 18:00 UTC, VoltrexMaster commented
> what is cl

Continuous integration.

2021-04-13 18:02 UTC, aflacc commented
> > what is cl
> 
> Continuous integration.

what is that

2021-04-13 18:06 UTC, VoltrexMaster commented
> > > what is cl
> > 
> > 
> > Continuous integration.
> 
> what is that

https://en.m.wikipedia.org/wiki/Continuous_integration

2021-04-13 18:06 UTC, aflacc commented
> > > > what is cl
> > > 
> > > 
> > > Continuous integration.
> > 
> > 
> > what is that
> 
> https://en.m.wikipedia.org/wiki/Continuous_integration

im too lazy

2021-04-13 18:16 UTC, actuallyasmartname requested changes

2021-04-13 18:16 UTC, actuallyasmartname commented on .github/workflows/ci.yml
> +on:
Probably should set this to all branches

2021-04-13 18:17 UTC, actuallyasmartname requested changes

2021-04-13 18:17 UTC, actuallyasmartname commented on .github/workflows/ci.yml
> +  workflow_dispatch:
probably should set this to all branches not just master

2024-05-08 00:25 UTC, closed without merging